service: jd-test-lambda-node

provider:
  name: aws
  region: us-west-2
  runtime: nodejs8.10

functions:
  app:
    handler: index-prod.handler
    events:
      - http:
          path: /
          method: get
          request:
            template:
              application/json: >
                {
                  "name": "$input.params('name')"
                }
      #- http: ANY /
      #- http: 'ANY {proxy+}'
